PROJECTS = [
    {
        "id": "assembly-defect",
        "title": "조립라인 불량 예측 및 최적화",
        "source": "DX추진랩",
        "domain": "생산/품질",
        "task": "예측·이상탐지",
        "data_type": "센서·이미지",
        "maturity": "운영",
        "access": "사내공유",
        "score": 96,
        "reuse": 42,
        "updated": "2026.06.12",
        "owner": "DX추진랩 / 제조AI셀",
        "license": "Internal Reuse",
        "description": "공정 센서, 검사 이미지, 이력 데이터를 결합하여 조립 불량 가능성을 사전에 예측하고 원인 후보를 제공합니다.",
        "impact": "불량 조기탐지 리드타임 35% 단축, 검사 샘플링 비용 18% 절감",
        "tags": ["불량예측", "이상탐지", "컴퓨터비전", "센서데이터", "제조AI"],
        "inputs": [
            ["line_id", "string", "조립 라인 또는 셀 ID"],
            ["timestamp", "datetime", "센서 측정 시각"],
            ["torque", "float", "체결 토크 값"],
            ["vision_zip", "file", "검사 이미지 묶음"],
            ["temperature", "float", "주요 설비 온도"],
        ],
        "outputs": [
            ["defect_probability", "float", "0~1 불량 가능성"],
            ["defect_type", "string", "예상 불량 유형"],
            ["root_cause_rank", "array", "상위 원인 후보"],
            ["recommended_action", "string", "조치 권고"],
        ],
        "files": [
            ["sample_data.csv", "2.4MB"],
            ["code_bundle.zip", "18.6MB"],
            ["model_weight.onnx", "94MB"],
            ["model_card.pdf", "1.2MB"],
            ["api_spec.yaml", "48KB"],
        ],
        "governance": [
            "데이터 비식별 처리 완료",
            "모델 카드 승인 완료",
            "ONNX 재현성 테스트 통과",
            "운영 모니터링 대시보드 연결",
        ],
    },
    {
        "id": "spec-rag",
        "title": "도면·사양서 RAG 질의응답",
        "source": "Learning Lab",
        "domain": "R&D/설계",
        "task": "RAG·문서검색",
        "data_type": "PDF·문서",
        "maturity": "검증완료",
        "access": "권한승인",
        "score": 91,
        "reuse": 37,
        "updated": "2026.06.07",
        "owner": "Learning Lab 4기 / 설계검색팀",
        "license": "Restricted Internal",
        "description": "도면, 사양서, 표준 문서를 벡터화하여 설계 담당자 질문에 근거 문서와 함께 답변합니다.",
        "impact": "설계 문서 검색 시간 60% 단축, 반복 질의 자동화",
        "tags": ["RAG", "문서검색", "사양서", "설계지원", "LLM"],
        "inputs": [
            ["question", "string", "사용자 질문"],
            ["document_set", "file", "PDF 또는 DOCX 묶음"],
            ["top_k", "integer", "검색 문단 수"],
            ["permission_group", "string", "문서 접근 권한 그룹"],
        ],
        "outputs": [
            ["answer", "string", "근거 기반 답변"],
            ["citations", "array", "참조 문서와 페이지"],
            ["confidence", "float", "답변 신뢰도"],
            ["followup_questions", "array", "후속 질문 추천"],
        ],
        "files": [
            ["sample_questions.json", "210KB"],
            ["rag_pipeline.zip", "24MB"],
            ["embedding_config.json", "33KB"],
            ["model_card.pdf", "1.6MB"],
            ["api_spec.yaml", "52KB"],
        ],
        "governance": [
            "문서 권한 그룹 매핑 완료",
            "답변 근거 표시 필수",
            "프롬프트 인젝션 방어 룰 적용",
            "로그 마스킹 적용",
        ],
    },
    {
        "id": "parts-forecast",
        "title": "부품 수요 예측 Forecasting",
        "source": "현업 주도",
        "domain": "SCM/구매",
        "task": "시계열예측",
        "data_type": "ERP·시계열",
        "maturity": "PoC",
        "access": "사내공유",
        "score": 84,
        "reuse": 25,
        "updated": "2026.05.29",
        "owner": "구매기획팀",
        "license": "Internal Reuse",
        "description": "월별 판매, 생산계획, 리드타임, 공급 리스크 데이터를 활용하여 부품 수요와 안전재고를 예측합니다.",
        "impact": "부품 과잉재고 12% 절감 가능성 확인",
        "tags": ["Forecasting", "수요예측", "재고최적화", "ERP", "구매"],
        "inputs": [
            ["part_no", "string", "부품 번호"],
            ["month", "date", "예측 기준월"],
            ["sales_plan", "float", "판매 계획"],
            ["lead_time", "integer", "조달 리드타임"],
            ["inventory", "integer", "현재 재고"],
        ],
        "outputs": [
            ["forecast_qty", "integer", "예측 수량"],
            ["safety_stock", "integer", "권장 안전재고"],
            ["risk_level", "string", "수급 리스크 등급"],
            ["drivers", "array", "예측 영향 요인"],
        ],
        "files": [
            ["sample_forecast.xlsx", "680KB"],
            ["forecast_notebook.zip", "9.8MB"],
            ["model_weight.pkl", "12MB"],
            ["model_card.pdf", "900KB"],
            ["api_spec.yaml", "40KB"],
        ],
        "governance": [
            "PoC 성능 기준 충족",
            "ERP 연동 전 보안 검토 필요",
            "현업 검증 데이터셋 보강 예정",
        ],
    },
    {
        "id": "fault-log",
        "title": "설비 로그 기반 고장 원인 분류",
        "source": "Learning Lab",
        "domain": "생산/품질",
        "task": "분류·진단",
        "data_type": "로그·센서",
        "maturity": "운영전환",
        "access": "사내공유",
        "score": 88,
        "reuse": 31,
        "updated": "2026.06.02",
        "owner": "Learning Lab 5기 / 설비보전",
        "license": "Internal Reuse",
        "description": "설비 이벤트 로그와 센서 시계열을 분석하여 고장 원인 후보와 점검 우선순위를 분류합니다.",
        "impact": "설비 보전 초동 분석 시간 45% 감소",
        "tags": ["설비보전", "로그분석", "분류", "이상탐지", "Root Cause"],
        "inputs": [
            ["equipment_id", "string", "설비 ID"],
            ["event_log", "file", "설비 이벤트 로그"],
            ["sensor_window", "array", "최근 센서 윈도우"],
            ["alarm_code", "string", "알람 코드"],
        ],
        "outputs": [
            ["fault_class", "string", "고장 유형"],
            ["cause_rank", "array", "원인 후보 순위"],
            ["inspection_priority", "string", "점검 우선순위"],
            ["similar_cases", "array", "유사 과거 사례"],
        ],
        "files": [
            ["sample_log.jsonl", "3.1MB"],
            ["fault_classifier.zip", "16MB"],
            ["model_weight.pt", "71MB"],
            ["model_card.pdf", "1.1MB"],
            ["api_spec.yaml", "46KB"],
        ],
        "governance": [
            "운영 전환 심사 진행",
            "센서 데이터 품질 룰 정의",
            "알람 코드 표준 매핑 완료",
        ],
    },
    {
        "id": "quote-summary",
        "title": "구매 견적 자동 요약·비교",
        "source": "현업 주도",
        "domain": "SCM/구매",
        "task": "요약·분류",
        "data_type": "문서·테이블",
        "maturity": "검증완료",
        "access": "권한승인",
        "score": 79,
        "reuse": 18,
        "updated": "2026.05.21",
        "owner": "구매전략팀",
        "license": "Restricted Internal",
        "description": "협력사 견적서와 조건표를 자동 요약하고 가격, 납기, 품질 조건 차이를 비교합니다.",
        "impact": "견적 1차 검토 소요시간 50% 단축",
        "tags": ["문서요약", "견적비교", "구매", "LLM", "표추출"],
        "inputs": [
            ["quote_files", "file", "견적서 PDF/XLSX"],
            ["comparison_axis", "array", "가격·납기·품질 등 비교 축"],
            ["supplier_meta", "table", "협력사 정보"],
        ],
        "outputs": [
            ["summary", "string", "견적 요약"],
            ["comparison_table", "table", "비교표"],
            ["risk_flags", "array", "주의 조건"],
            ["recommendation", "string", "검토 의견 초안"],
        ],
        "files": [
            ["sample_quotes.zip", "4.2MB"],
            ["quote_agent.zip", "14MB"],
            ["prompt_template.md", "28KB"],
            ["model_card.pdf", "1.0MB"],
            ["api_spec.yaml", "44KB"],
        ],
        "governance": [
            "협력사 정보 접근권한 필요",
            "민감정보 마스킹 적용",
            "LLM 답변 검토자 승인 필수",
        ],
    },
    {
        "id": "vision-segmentation",
        "title": "검사 이미지 결함 세그멘테이션",
        "source": "DX추진랩",
        "domain": "생산/품질",
        "task": "컴퓨터비전",
        "data_type": "이미지",
        "maturity": "운영",
        "access": "사내공유",
        "score": 93,
        "reuse": 34,
        "updated": "2026.06.10",
        "owner": "DX추진랩 / Vision AI",
        "license": "Internal Reuse",
        "description": "검사 이미지에서 결함 영역을 픽셀 단위로 검출하고 결함 크기, 위치, 유형을 구조화합니다.",
        "impact": "육안 검사 편차 감소, 결함 위치 정량화",
        "tags": ["Segmentation", "검사이미지", "결함검출", "컴퓨터비전", "품질"],
        "inputs": [
            ["image", "file", "검사 이미지"],
            ["product_type", "string", "제품군"],
            ["threshold", "float", "결함 판정 임계값"],
        ],
        "outputs": [
            ["mask_image", "file", "결함 마스크"],
            ["defect_area", "float", "결함 면적"],
            ["defect_label", "string", "결함 유형"],
            ["confidence", "float", "신뢰도"],
        ],
        "files": [
            ["sample_images.zip", "38MB"],
            ["segmentation_code.zip", "31MB"],
            ["model_weight.onnx", "126MB"],
            ["model_card.pdf", "1.4MB"],
            ["api_spec.yaml", "48KB"],
        ],
        "governance": [
            "검사 이미지 반출 금지",
            "익명 샘플만 제공",
            "GPU 실행 환경 검증 완료",
        ],
    },
    {
        "id": "bi-anomaly",
        "title": "BI 대시보드 이상 신호 알림",
        "source": "운영 자산",
        "domain": "경영/공통",
        "task": "이상탐지",
        "data_type": "DB·BI",
        "maturity": "운영",
        "access": "사내공유",
        "score": 82,
        "reuse": 51,
        "updated": "2026.06.04",
        "owner": "데이터플랫폼팀",
        "license": "Internal Service",
        "description": "BI 지표의 급변, 누락, 패턴 이탈을 감지하여 담당자에게 알림과 원인 분석 후보를 제공합니다.",
        "impact": "지표 누락 감지 자동화, 반복 모니터링 업무 절감",
        "tags": ["BI", "이상탐지", "알림", "대시보드", "운영자산"],
        "inputs": [
            ["metric_id", "string", "BI 지표 ID"],
            ["value_series", "array", "지표 시계열"],
            ["calendar", "table", "영업일·이벤트 캘린더"],
        ],
        "outputs": [
            ["anomaly_score", "float", "이상 점수"],
            ["alert_level", "string", "알림 레벨"],
            ["reason_hint", "array", "원인 후보"],
            ["dashboard_link", "url", "관련 대시보드 링크"],
        ],
        "files": [
            ["sample_metric.csv", "450KB"],
            ["anomaly_service.zip", "13MB"],
            ["model_weight.pkl", "8MB"],
            ["service_card.pdf", "760KB"],
            ["api_spec.yaml", "36KB"],
        ],
        "governance": [
            "서비스 운영 SLA 정의",
            "대시보드 권한 연동",
            "알림 로그 보관 정책 적용",
        ],
    },
    {
        "id": "safety-chatbot",
        "title": "안전 작업 표준서 챗봇",
        "source": "Learning Lab",
        "domain": "안전/환경",
        "task": "RAG·챗봇",
        "data_type": "문서",
        "maturity": "PoC",
        "access": "사내공유",
        "score": 76,
        "reuse": 15,
        "updated": "2026.05.16",
        "owner": "EHS 혁신TF",
        "license": "Internal Reuse",
        "description": "작업 표준서와 안전 매뉴얼을 검색하여 작업 단계별 유의사항과 점검 항목을 답변합니다.",
        "impact": "신입 작업자 표준서 탐색 시간 단축",
        "tags": ["안전", "챗봇", "RAG", "표준서", "EHS"],
        "inputs": [
            ["question", "string", "작업자 질문"],
            ["site", "string", "사업장"],
            ["manual_set", "file", "표준서 문서 묶음"],
        ],
        "outputs": [
            ["answer", "string", "답변"],
            ["safety_checklist", "array", "점검 항목"],
            ["citations", "array", "근거 문서"],
            ["warning", "string", "고위험 작업 안내"],
        ],
        "files": [
            ["sample_manuals.zip", "8MB"],
            ["safety_rag.zip", "19MB"],
            ["prompt_guardrails.md", "35KB"],
            ["model_card.pdf", "1.0MB"],
            ["api_spec.yaml", "42KB"],
        ],
        "governance": [
            "고위험 작업 법규 문구 검토 필요",
            "현장별 문서 최신성 관리 필요",
            "답변 면책 문구 적용",
        ],
    },
]

PERFORMANCE_PROFILES = {
    "assembly-defect": {
        "grade": "A",
        "title": "불량 예측 모델 검증 결과",
        "summary": "8개 조립라인 센서 46,200건과 검사 이미지 12,400장을 기준으로 사전 불량 탐지 성능과 현장 알림 품질을 검증했습니다.",
        "metrics": [
            {"label": "AUROC", "value": "0.94", "bar": 94, "note": "불량/정상 구분력"},
            {"label": "F1 Score", "value": "0.88", "bar": 88, "note": "정밀도와 재현율 균형"},
            {"label": "High-risk Recall", "value": "91%", "bar": 91, "note": "고위험 불량 사전 포착률"},
            {"label": "False Alarm Rate", "value": "5.8%", "bar": 76, "note": "라인 담당자 피로도 관리 기준"},
        ],
        "bar_title": "결함 유형별 탐지율",
        "bars": [["체결 토크 편차", 93, "93%"], ["누락/미체결", 88, "88%"], ["표면 스크래치", 84, "84%"], ["센서 드리프트", 90, "90%"]],
        "notes": [["검증 기간", "2026.03~2026.05 양산 라인 샘플"], ["판정 기준", "불량 가능성 0.72 이상이면 고위험 알림"], ["운영 목표", "미검출률 8% 이하, 오탐률 7% 이하 유지"]],
        "table_title": "혼동 행렬 요약",
        "headers": ["구분", "건수", "운영 해석"],
        "rows": [["불량 정탐", "842건", "사전 선별 후 품질 검사 강화"], ["정상 정탐", "10,923건", "정상 통과 데이터"], ["미검출", "74건", "임계값 재조정 대상"], ["오탐", "671건", "알림 피로도 모니터링 대상"]],
        "monitoring": ["라인/품목 변경 시 데이터 drift 점검", "일별 오탐률 8% 초과 시 임계값 재검토", "원인 후보 Top-3 적중률을 월 단위 리뷰"],
    },
    "spec-rag": {
        "grade": "A-",
        "title": "RAG 검색·답변 품질 평가",
        "summary": "설계 사양 QA 420건과 표준문서 3,200페이지를 기준으로 검색 재현율, 근거 충실도, 인용 커버리지를 평가했습니다.",
        "metrics": [
            {"label": "Retrieval Recall@5", "value": "0.89", "bar": 89, "note": "정답 근거 문단 검색률"},
            {"label": "Faithfulness", "value": "0.93", "bar": 93, "note": "근거 외 생성 억제"},
            {"label": "Answer Accuracy", "value": "0.86", "bar": 86, "note": "전문가 평가 정답률"},
            {"label": "Citation Coverage", "value": "96%", "bar": 96, "note": "페이지/문서 인용 포함률"},
        ],
        "bar_title": "평가 축별 품질 점수",
        "bars": [["검색 품질", 89, "0.89"], ["답변 정확도", 86, "0.86"], ["근거 충실도", 93, "0.93"], ["권한 필터링", 98, "0.98"]],
        "notes": [["평가 데이터", "설계 변경, 체결, 소재, 공차 관련 질의"], ["Pass 기준", "인용 누락 5% 이하, 권한 문서 미노출 100%"], ["주요 리스크", "오래된 사양서와 최신 표준 간 충돌"]],
        "table_title": "RAG 컴포넌트별 평가",
        "headers": ["컴포넌트", "지표", "결과"],
        "rows": [["Retriever", "MRR@10", "0.81"], ["Reranker", "nDCG@5", "0.87"], ["Generator", "Hallucination Rate", "2.6%"], ["Guardrail", "Prompt Injection Block", "99.1%"]],
        "monitoring": ["문서 업데이트 후 임베딩 재색인 상태 점검", "답변에 citation이 없는 경우 사용자 노출 제한", "권한 그룹별 검색 결과 누락/과노출 로그 점검"],
    },
    "parts-forecast": {
        "grade": "B+",
        "title": "부품 수요 예측 성능",
        "summary": "18개월 ERP 수요·재고·리드타임 데이터를 기준으로 예측 오차와 안전재고 추천 효과를 평가했습니다.",
        "metrics": [
            {"label": "MAPE", "value": "8.7%", "bar": 91, "note": "월별 수요 예측 평균 오차"},
            {"label": "WAPE", "value": "7.2%", "bar": 93, "note": "물량 가중 오차"},
            {"label": "RMSE", "value": "326EA", "bar": 84, "note": "품목별 수량 오차"},
            {"label": "Stockout Hit", "value": "82%", "bar": 82, "note": "결품 위험 사전 감지율"},
        ],
        "bar_title": "품목군별 예측 정확도",
        "bars": [["동력전달 부품", 92, "92%"], ["공작기계 부품", 87, "87%"], ["전장 부품", 83, "83%"], ["장납기 부품", 78, "78%"]],
        "notes": [["검증 방식", "Rolling 3개월 Backtesting"], ["Pass 기준", "MAPE 10% 이하, 결품 위험 Hit 80% 이상"], ["개선 필요", "프로모션/긴급오더 변수 추가 필요"]],
        "table_title": "Backtesting 결과",
        "headers": ["월", "Actual", "Forecast", "오차율"],
        "rows": [["2026.03", "14,820", "14,120", "4.7%"], ["2026.04", "15,240", "16,010", "5.1%"], ["2026.05", "13,910", "12,620", "9.3%"], ["2026.06", "16,300", "15,870", "2.6%"]],
        "monitoring": ["품목군별 MAPE가 12% 초과하면 재학습 후보 등록", "ERP 실적 데이터 적재 지연 여부 점검", "안전재고 추천값과 실제 결품 발생률 비교"],
    },
    "fault-log": {
        "grade": "A-",
        "title": "설비 고장 원인 분류 평가",
        "summary": "설비 이벤트 로그 1.8M건과 고장 조치 이력 7,600건을 기준으로 원인 분류 정확도와 Top-K 진단 성능을 검증했습니다.",
        "metrics": [
            {"label": "Macro F1", "value": "0.84", "bar": 84, "note": "고장 유형 간 균형 성능"},
            {"label": "Top-3 Cause Hit", "value": "92%", "bar": 92, "note": "원인 후보 Top-3 적중률"},
            {"label": "Precision", "value": "0.87", "bar": 87, "note": "불필요 점검 억제"},
            {"label": "MTTD 감소", "value": "45%", "bar": 90, "note": "초동 진단 시간 절감"},
        ],
        "bar_title": "고장 유형별 F1",
        "bars": [["베어링 마모", 86, "0.86"], ["윤활 부족", 82, "0.82"], ["센서 오프셋", 88, "0.88"], ["구동부 과열", 80, "0.80"]],
        "notes": [["검증 범위", "창원1/2공장 핵심 설비 로그"], ["Pass 기준", "Top-3 원인 적중률 90% 이상"], ["현장 적용", "보전 담당자 검토 후 조치 등록"]],
        "table_title": "진단 클래스별 운영 기준",
        "headers": ["고장 클래스", "권장 우선순위", "알림 기준"],
        "rows": [["구동계 이상", "High", "온도/진동 동시 급등"], ["센서 계측 오류", "Medium", "오프셋 지속 30분 이상"], ["유압 계통", "High", "압력 변동성 임계 초과"], ["소모품 마모", "Medium", "누적 가동시간+로그 패턴"]],
        "monitoring": ["신규 알람 코드 발생 시 라벨 매핑 요청", "진단 결과와 실제 조치 코드 불일치율 관리", "설비 교체/정비 후 재학습 필요 여부 검토"],
    },
    "quote-summary": {
        "grade": "B+",
        "title": "견적 문서 추출·요약 품질",
        "summary": "협력사 견적서 PDF/XLSX 260세트를 기준으로 표 추출 정확도, 비교 요약 완성도, 검토자 수정률을 평가했습니다.",
        "metrics": [
            {"label": "Extraction Acc.", "value": "91%", "bar": 91, "note": "가격/납기/조건 필드 추출"},
            {"label": "Table F1", "value": "0.86", "bar": 86, "note": "표 구조 복원 성능"},
            {"label": "Summary Complete", "value": "88%", "bar": 88, "note": "핵심 조건 포함률"},
            {"label": "Reviewer Edit", "value": "14%", "bar": 86, "note": "검토자 수정 발생률"},
        ],
        "bar_title": "비교 축별 추출 정확도",
        "bars": [["단가", 94, "94%"], ["납기", 90, "90%"], ["보증 조건", 83, "83%"], ["예외 조항", 79, "79%"]],
        "notes": [["평가 데이터", "협력사 32개사 견적서 샘플"], ["Pass 기준", "핵심 필드 추출 90% 이상"], ["주의 사항", "스캔본 품질 낮을 때 OCR 보정 필요"]],
        "table_title": "검토자 평가 요약",
        "headers": ["항목", "평균 점수", "주요 보완점"],
        "rows": [["가격 비교", "4.6/5", "통화 단위 자동 정규화"], ["납기 비교", "4.4/5", "영업일/달력일 구분"], ["리스크 플래그", "4.1/5", "예외 조항 탐지 보강"], ["추천 의견", "4.0/5", "부서별 평가 기준 반영"]],
        "monitoring": ["협력사 민감정보 마스킹 누락률 점검", "검토자 수정 로그를 프롬프트 개선 데이터로 축적", "표 추출 실패 문서를 재처리 큐로 이동"],
    },
    "vision-segmentation": {
        "grade": "A",
        "title": "결함 세그멘테이션 성능",
        "summary": "제품군별 검사 이미지 18,600장과 픽셀 라벨을 기준으로 결함 영역 검출 정밀도와 실시간 추론 속도를 평가했습니다.",
        "metrics": [
            {"label": "mIoU", "value": "0.83", "bar": 83, "note": "마스크 영역 일치도"},
            {"label": "Dice Score", "value": "0.89", "bar": 89, "note": "결함 영역 중첩률"},
            {"label": "Pixel Precision", "value": "0.91", "bar": 91, "note": "오검출 픽셀 비율 관리"},
            {"label": "Latency", "value": "38ms", "bar": 94, "note": "이미지 1장당 GPU 추론"},
        ],
        "bar_title": "결함 유형별 Dice Score",
        "bars": [["스크래치", 90, "0.90"], ["찍힘", 86, "0.86"], ["오염", 84, "0.84"], ["미세 크랙", 78, "0.78"]],
        "notes": [["검증 이미지", "제품군 5종, 조명 조건 4종"], ["Pass 기준", "mIoU 0.80 이상, latency 50ms 이하"], ["운영 한계", "신규 조명/카메라 각도 변경 시 재검증"]],
        "table_title": "이미지 품질 조건별 결과",
        "headers": ["조건", "mIoU", "운영 판단"],
        "rows": [["정상 조명", "0.86", "운영 가능"], ["저조도", "0.79", "보정 필요"], ["반사 심함", "0.76", "재촬영 권고"], ["고해상도", "0.85", "운영 가능"]],
        "monitoring": ["카메라 교체/조명 변경 시 샘플 200장 재검증", "결함 마스크 면적 분포 drift 점검", "미세 크랙 클래스 데이터 보강"],
    },
    "bi-anomaly": {
        "grade": "A-",
        "title": "BI 지표 이상탐지 알림 품질",
        "summary": "주요 BI 지표 74개와 과거 장애/누락 이벤트 1,120건을 기준으로 알림 정밀도와 탐지 지연 시간을 평가했습니다.",
        "metrics": [
            {"label": "Precision", "value": "0.90", "bar": 90, "note": "유효 알림 비율"},
            {"label": "Recall", "value": "0.84", "bar": 84, "note": "이상 이벤트 포착률"},
            {"label": "Detection Lag", "value": "1.2d", "bar": 88, "note": "중앙 탐지 지연 시간"},
            {"label": "Noise 감소", "value": "31%", "bar": 89, "note": "기존 룰 대비 알림 감소"},
        ],
        "bar_title": "지표 유형별 탐지 품질",
        "bars": [["품질 지표", 91, "0.91"], ["재무 지표", 86, "0.86"], ["생산 지표", 88, "0.88"], ["시스템 지표", 83, "0.83"]],
        "notes": [["검증 기준", "과거 알림 로그와 담당자 판정 결과"], ["Pass 기준", "Precision 0.85 이상, Lag 2일 이하"], ["운영 정책", "High 알림은 Teams/메일 동시 발송"]],
        "table_title": "알림 레벨별 운영 기준",
        "headers": ["레벨", "조건", "조치"],
        "rows": [["High", "anomaly_score 0.85 이상", "담당자 즉시 알림"], ["Medium", "0.65~0.85", "일일 리포트 포함"], ["Low", "0.45~0.65", "대시보드 표시만"], ["No Alert", "0.45 미만", "로그 저장"]],
        "monitoring": ["지표별 계절성/영업일 캘린더 업데이트", "알림 미확인 건 자동 리마인드", "담당자 피드백으로 threshold 월별 보정"],
    },
    "safety-chatbot": {
        "grade": "B+",
        "title": "안전 표준서 챗봇 평가",
        "summary": "작업 표준서 610건과 안전 질의 380건을 기준으로 근거 기반 답변, 고위험 작업 차단, 체크리스트 생성 품질을 평가했습니다.",
        "metrics": [
            {"label": "Groundedness", "value": "0.91", "bar": 91, "note": "표준서 근거 기반 답변"},
            {"label": "Safety Rule Pass", "value": "98%", "bar": 98, "note": "고위험 안내 룰 준수"},
            {"label": "Answer Accuracy", "value": "0.84", "bar": 84, "note": "EHS 담당자 평가"},
            {"label": "Escalation Recall", "value": "93%", "bar": 93, "note": "관리자 문의 전환 포착"},
        ],
        "bar_title": "질문 유형별 답변 품질",
        "bars": [["작업 전 점검", 89, "0.89"], ["보호구 기준", 87, "0.87"], ["비상 대응", 82, "0.82"], ["고위험 작업", 93, "0.93"]],
        "notes": [["평가 문서", "사업장별 안전 매뉴얼/작업 표준서"], ["Pass 기준", "고위험 질의는 담당자 확인 안내 필수"], ["개선 필요", "현장별 최신 표준서 동기화"]],
        "table_title": "Guardrail 평가",
        "headers": ["시나리오", "통과율", "필수 응답 정책"],
        "rows": [["잠금/표지 절차", "99%", "LOTO 확인 안내"], ["고소 작업", "98%", "관리감독자 승인 안내"], ["화기 작업", "97%", "허가서/소화설비 확인"], ["응급 상황", "100%", "즉시 신고 우선 안내"]],
        "monitoring": ["법규/표준서 개정 시 재색인 알림", "고위험 답변에 면책 및 담당자 확인 문구 포함 여부 점검", "현장 사용자 피드백 기반 FAQ 보강"],
    },
}

SOURCE_OPTIONS = ["Learning Lab", "DX추진랩", "현업 주도", "운영 자산"]

TEMPLATE_OPTIONS = [
    "LLM 자동 선택 · Repository/Artifact Scanner",
    "Classification · Python Predict Handler",
    "MLflow PyFunc Template",
    "Vision · ONNX Runtime Template",
    "Forecasting · Batch Evaluation Template",
    "RAG/LLM · Golden QA Evaluation Template",
    "Optimization · Simulation Adapter Template",
]

FILTER_GROUPS = [
    {"key": "source", "title": "등록 출처", "options": SOURCE_OPTIONS},
    {"key": "domain", "title": "업무 영역", "options": ["생산/품질", "R&D/설계", "SCM/구매", "경영/공통", "안전/환경"]},
    {"key": "task", "title": "Task 유형", "options": ["예측·이상탐지", "RAG·문서검색", "시계열예측", "분류·진단", "요약·분류", "컴퓨터비전", "이상탐지", "RAG·챗봇"]},
    {"key": "data_type", "title": "Data Type", "options": ["센서·이미지", "PDF·문서", "ERP·시계열", "로그·센서", "문서·테이블", "이미지", "DB·BI", "문서"]},
    {"key": "maturity", "title": "자산 성숙도", "options": ["PoC", "검증완료", "운영전환", "운영"]},
    {"key": "access", "title": "접근 권한", "options": ["사내공유", "권한승인"]},
]

IMPACT_BASELINE = {
    "registered_assets": 128,
    "operating_assets": 42,
    "verified_assets": 61,
    "total_reuse": 1847,
    "expected_effect": "3.8억",
    "pending": 7,
}

IMPACT_MONTHLY = [
    {"month": "1월", "registered": 22, "adopted": 8},
    {"month": "2월", "registered": 34, "adopted": 13},
    {"month": "3월", "registered": 52, "adopted": 21},
    {"month": "4월", "registered": 75, "adopted": 29},
    {"month": "5월", "registered": 101, "adopted": 36},
    {"month": "6월", "registered": 128, "adopted": 42},
]

BOOKMARKS = ["assembly-defect", "spec-rag", "parts-forecast"]

QA_POSTS = {
    "assembly-defect": [
        {"author": "김민수", "author_dept": "품질혁신팀", "content": "조립 셀별 threshold를 다르게 적용할 수 있나요?", "created_at": "2026-06-13 09:20"},
        {"author": "오세정", "author_dept": "DX추진랩", "content": "가능합니다. 라인별 calibration 파일을 같이 배포하면 됩니다.", "created_at": "2026-06-13 11:05"},
    ],
    "spec-rag": [
        {"author": "박지훈", "author_dept": "설계1팀", "content": "권한 그룹별로 색인 인덱스를 분리했는지 궁금합니다.", "created_at": "2026-06-09 15:10"},
    ],
}

PLACEHOLDER_PAGES = [
    {
        "slug": "newsletter",
        "title": "AI Trend News Letter",
        "description": "뉴스레터 발행 화면 골격입니다.",
        "status": "준비 중",
        "body": "발행 이력, 구독 대상, 큐레이션 카드, 예약 발송 영역만 우선 배치했습니다. 실제 에디터와 발송 워크플로는 다음 단계에서 연결하면 됩니다.",
        "cta_label": "초안 작성",
    },
    {
        "slug": "ask-anything",
        "title": "AI 무엇이든 물어보살",
        "description": "질문 등록과 답변 현황 화면 골격입니다.",
        "status": "준비 중",
        "body": "카테고리 필터, 질문 작성 폼, 최근 답변 리스트, 담당자 라우팅 영역만 구성했습니다. 실제 알림과 SLA 로직은 미구현입니다.",
        "cta_label": "질문 등록",
    },
    {
        "slug": "best-practice",
        "title": "AI 활용 Best Practice 공유",
        "description": "사례 등록 화면 골격입니다.",
        "status": "준비 중",
        "body": "적용 조직, 개선 지표, 재사용 팁, 첨부자료 영역만 배치했습니다. 승인 워크플로와 템플릿 관리 기능은 후속 구현 대상입니다.",
        "cta_label": "사례 등록",
    },
    {
        "slug": "case-register",
        "title": "적용 사례 등록",
        "description": "현업 사례 등록 페이지 골격입니다.",
        "status": "준비 중",
        "body": "성과 수치, 전후 비교, 산출물 링크, 리뷰어 승인 메모를 넣을 수 있는 폼 구조만 구현했습니다.",
        "cta_label": "임시 저장",
    },
]

AUTO_CHECK_RESULT = {
    "task": "컴퓨터비전",
    "data_type": "이미지",
    "template": "Vision · ONNX Runtime Template",
    "metric_preset": "Vision · mAP/IoU/Latency",
    "renderer": "Vision · Image Overlay / Segmentation",
    "tags": ["컴퓨터비전", "표면결함", "객체탐지", "이미지검사", "제조AI", "품질검사"],
    "description": "라인스캔 이미지에서 스크래치·찍힘·이물 등 표면 결함을 탐지하고 위치와 신뢰도를 반환하는 비전 검사 자산입니다. 유사 검사 공정에 재사용할 수 있도록 ONNX Runtime 기반 추론 코드와 테스트셋 평가 구성을 포함합니다.",
    "input_schema": "image: PNG/JPEG, 4096px line-scan\nroi_config: JSON, 검사영역 및 threshold\nlot_id: string, 생산 LOT 식별자",
    "output_schema": "detections: array<object>, class/box/score\ndefect_map: PNG overlay\ngrade: enum[OK, REWORK, NG]\nlatency_ms: float",
    "endpoint": "src/inference_handler.py::predict",
    "threshold": "mAP@0.5 ≥ 0.90, Recall ≥ 0.88, Latency P95 ≤ 80ms",
    "governance": "PII 없음, 사내 이미지 반출 금지, 모델/데이터 카드 초안 생성 완료, secret scan 통과, 운영 후 drift 모니터링 필요",
    "checks": [
        {"label": "REPOSITORY SCAN", "title": "필수 구조 8/9개 확인", "description": "README, src, model, tests, requirements, sample_result를 확인했습니다. dataset_card 초안은 보완이 필요합니다."},
        {"label": "TEMPLATE RECOMMEND", "title": "Vision · ONNX Runtime Template", "description": "predict(image, roi_config) 흐름과 ONNX weight가 확인되어 비전 템플릿을 추천합니다."},
        {"label": "METRIC PRESET", "title": "mAP / IoU / Recall / Latency", "description": "객체탐지 성격으로 분류되어 Vision 평가 지표와 threshold 초안을 생성했습니다."},
        {"label": "GOVERNANCE CHECK", "title": "주의 1건 · 통과 5건", "description": "개인정보와 secret은 없고, 테스트셋 카드의 촬영 조건 설명만 보강이 필요합니다."},
    ],
}
